
---
title: "1918 Pandemic and COVID-19"
author: 
  - Myra Li
  - Randall Ni
  - Faustine Fan
thanks: "Code and data are available at: https://github.com/Faustine123/1918-INFLUENZA-PANDEMIC-COVID-19.git"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "A"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(palmerpenguins)
library(dplyr)
library(tidyr)
library(readxl)
library(data.table)
library(lubridate)
library(haven)
library(readxl)
library(ggplot2)
raw_data_fig1<-read_dta(here::here("Input/Data/LOC_Newspapers_Sep18_Dec19.dta"))
raw_data_fig2<-read_dta(here::here("Input/Data/Life_Expectancy.dta"))
```

```{r}
########Figure #########
cleaned_figure1_data <-
  raw_data_fig1 |>
  # Select only certain columns
  select(
   flu_sep1_1918_dec31_1919,
   year,
   month,
   region
  )

### Clean data ###
# Rename column
cleaned_figure1_data <-
 cleaned_figure1_data |>
  rename(
    influence = flu_sep1_1918_dec31_1919
  )

#group by year, month, and region
cleaned_figure1_data<- cleaned_figure1_data %>%
  group_by(year, month, region) %>%
  summarize(total_influence = sum(influence)) %>%
  ungroup()

#create a new column to store date in month.year format
cleaned_figure1_data$date_label <- format(as.Date(paste(cleaned_figure1_data$year, cleaned_figure1_data$month, "01", sep = "-")), "%b.%Y")
cleaned_figure1_data$date_label <- factor(cleaned_figure1_data$date_label, levels = unique(cleaned_figure1_data$date_label))

#store cleaned data for figure 1
write.csv(cleaned_figure1_data, file = here::here("Output/Data/cleaned_figure1_data.csv"), row.names = FALSE)

### Draw graph ###
ggplot(cleaned_figure1_data, aes(x = date_label, y = total_influence, group = region, color = region)) +
  geom_line() +
  scale_x_discrete(labels = c("Sep.1918","", "Nov.1918","", "Jan.1919","","Mar.1919","", "May.1919","","Jul.1919","","Sep.1919","","Nov.1919","")) +
  labs(x = "Publication Month", y = "Articles mentioning influenza")

```

```{r}
######### Figure 2 ############
### Clean data ###
# Select only certain columns
cleaned_figure2_data <-
  raw_data_fig2 |>
  select(
   entity,
   year,
   lifeexpectancyyears
  )
cleaned_figure2_data <- cleaned_figure2_data %>%
  filter(year >= 1900, year <= 1940)

#calculate the mean of life expectanacy years
calculate_mean<- cleaned_figure2_data %>%
  group_by(year) %>%
  summarize(average_life_expectancy = mean(lifeexpectancyyears)) %>%
  ungroup()

#add lines
add_number <- calculate_mean %>% 
  select(year) %>% 
  n_distinct()
added_data <- data.frame(
  year = rep(1900:1940, each = 1),
  entity = rep("average", add_number),
  lifeexpectancyyears = numeric(add_number)
)

#combine table together
final_figure2_data <- rbind(cleaned_figure2_data, added_data)

#replaced the average life expectancy years
final_figure2_data$lifeexpectancyyears[
  final_figure2_data$entity == "average"] <- 
  calculate_mean$average_life_expectancy[
      calculate_mean$year == final_figure2_data$year[
        final_figure2_data$entity == "average"]]

#store cleaned data for figure 2
write.csv(final_figure2_data, file = here::here("Output/Data/cleaned_figure2_data.csv"), row.names = FALSE)

###Draw graph###
new_dataset <- 
  final_figure2_data %>% 
  filter(entity %in% c("Italy","Denmark","average"))

ggplot(final_figure2_data, aes(
  x = year, 
  y = lifeexpectancyyears, 
  color = entity
  )) +
  geom_line(alpha = 0.2) +
  geom_line(data = new_dataset, aes(
  x = year, 
  y = lifeexpectancyyears, 
  color = entity
  )) +
  theme_minimal() +
  labs(
    x = "Year",
    y = "Period Life Expectancy Years",
    color = "Entity",
    caption = "Data source: World Bank."
  )
  
```

